version: "3.7"
# convenient compose file for Self-hosted LiveSync.
# Initial Author: @arminus
# Modified      : @vrtmrz
services:
    caddy:
        image: caddy:alpine
        ports:
            - 19778:80
        networks:
            - caddy
        volumes:
            - ./data/caddy:/data
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
        restart: always

    couchserver:
        image: couchdb:3.3
        ports:
            - 17788:5984
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PW}
        volumes:
            # The files' owner will be id:5984 when you launch the image.
            # Because CouchDB writes on-the-fly configurations into local.ini.
            # So when you want to perform git pull or change something, you have to change owners back.
            - ./data/couchdb:/opt/couchdb/data
            - ./conf/local.ini:/opt/couchdb/etc/local.ini
        restart: always

networks:
  caddy:
    external: true